### ISSUE TITLE
Non Binding - source property

### ISSUE THREAD

**Issue by jonniespratley** [PredixDev/px-api-viewer#2]
The source property is not data bound, therefore if one was to have multiple elements included in one parent element (nested element folders) when the value changes it should analyze the new source element. 

Also if one bundle includes many sub elements, loading API docs for the sub element is not possible.

**Comment by mdwragg** [comment]
Now generate static API via `polymer analyze` so no longer applicable - component generates all API applicable to the component and hands it over to this component.
